# Generated by Django 5.2.9 on 2025-12-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='song',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
