# Generated by Django 5.2.9 on 2026-01-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options_todo_created_at_todo_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
